name: spindle
channels:
  - pytorch
  - pyg
  - nvidia
  - defaults
dependencies:
  - pyg=2.4.0
  - python=3.10
  - pytorch=2.1.2
  - pytorch-scatter=2.1.2
  - pip
  - pip:
      - git+https://github.com/konstantinosKokos/aethel@stable
      - transformers==4.39.1
